### ISSUE TITLE
Snelstart B2B API - add support for V2

### ISSUE THREAD

**Issue by fkwakkenbos** [avancecommunicatie/snelstart-b2b-api#3]
Could you please add support for V2 of the Snelstart B2B API ?
It's as simple by editing the protected $path URL...
https://github.com/avancecommunicatie/snelstart-b2b-api/blob/master/src/Snelstart/Snelstart.php#L11

Or make it dynamic by adding a setter for $path.

**Comment by MPaap** [comment]
Fix has been merged, Thank you for the contribution.
